apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../apps/flux-system/sbox/base
- ../../../apps/podinfo/base/kustomize.yaml
- ../../../apps/sources/base
- ../../../apps/infrastructure/base