apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: credentials-sync  # name must match the stub-resource in az-identity.yaml
  namespace: flux-system
spec:
  clientID: db28bc8d-9438-4750-9544-e4c8427e7c3f
  resourceID: /subscriptions/ea7d6031-5674-4635-9122-b7c31b5cdba3/resourceGroups/tamops-k8s-mi/providers/Microsoft.ManagedIdentity/userAssignedIdentities/tamops-aks-mi
  type: 0  # user-managed identity