apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/fluxcd/flux2/tree/main/manifests/integrations/registry-credentials-sync/azure?ref=main
patchesStrategicMerge:
  - config-patches.yaml